// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruwdujecanxepvyrhibd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1d2R1amVjYW54ZXB2eXJoaWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjY5MzEsImV4cCI6MjA3NDE0MjkzMX0.TwDywu_2HtLSZVM0J-ncwyyaUlKWMCcVeC-2kXZ7k48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});